# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d12dd1d4138fb5730b78ee218054c7d2bd4416f554bb2c6b79d7dfa264a4be6b20394feee60caa57d1c81082e67be3ab1fbae5e9f2f906e01de943502d41f15c

test:
  secret_key_base: 5dd221ba4102667967bd8208f514bf6178d0aa6e2a3036eb5f4b2426e97f87f8eccc807ed7de4fe3ea2c4743032f6557ac9850d9b405bd9300cae31d736a74bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
